export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const EMPTY_CART = "EMPTY_CART";
export const PRODUCT_LIST ="PRODUCT_LIST";
export const UPDATE_PRODUCT_COUNT ="UPDATE_PRODUCT_COUNT";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
